env:
  browser: true
  es2021: true
extends:
  - xo
  - eslint:recommended
  - 'plugin:vue/vue3-essential'
  - 'plugin:@typescript-eslint/recommended'
  - prettier
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
  - prettier
rules:
  prettier/prettier: error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
